<?php echo $this->doctype() ?>
<?php //echo $this->placeholder('header');    ?>

<html>
    <head>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Favicon -->
        <link rel="shortcut icon" href="/img/favicon.ico">
        <?php echo $this->headMeta() ?>
        <?php echo $this->headTitle() ?><br>
    <?php echo $this->headScript() ?><br>
    <?php echo $this->headLink() ?>


</head>
<body>

    <!-- NAVBAR
================================================== -->
    <!-- Modal -->
    <div id="about" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

            <h3 id="myModalLabel">Site para melhorar os parquinhos do Brasil</h3>
        </div>

        <div class="modal-body">
            <p>Parquinhos comunitários para todos</p>

            <p><strong>Autor:</strong> Turma dos Parquinhos (<a href="http://mundodosparquinhos.org">mundodosparquinhos.org</a>)</p>
        </div>

        <div class="modal-footer">
            <button class="btn" data-dismiss="modal" aria-hidden="true">OK</button>
        </div>
    </div>

    <div class="container">
        <div class="header">
            <div class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="brand">Bem-Vindo ao Mundo dos Parquinhos</a>
                        <div class="nav-collapse collapse">
                            <ul class="nav">
                                <!-- viewHelper url  one of the best veiew helpers-->
                                <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true) ?>"><i class="icon-home"></i> Início</a></li>


                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-building"></i> Temas <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'payment'), null, true) ?>">seguranca</a></li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'customer', 'action' => 'index'), null, true) ?>">Fotos</a></li>
                                        <li><a href="<?php echo $this->url(array('controller' => 'employees', 'action' => 'index'), null, true) ?>">Vida com parquinhos</a></li>
                                        <li><a href="#">Controle de Acesso</a></li>
                                        <li><a href="#"></a></li>

                                    </ul>
                                </li>

                                <li><a href="#" data-toggle="modal" data-target="#about"><i class="icon-info-sign"></i> Contato</a></li>

                            </ul>

                            <?php
                            if (!Zend_Auth::getInstance()->hasIdentity()) {
                                ?>
                                <ul class="nav pull-right">
                                    <li class="dropdown">
                                        <a href="" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user"></i> Entrar <b class="caret"></b></a>
                                        <div class="login-menu dropdown-menu well">

                                            <?php echo $this->layout()->varname; ?>


                                        </div>
                                    </li>
                                </ul>
                                <?php
                            } else {
                                ?>
                            <ul class="nav pull-right">
                                <li><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'authentication', 'action' => 'logout'), null, true) ?>" >Abmelden </li>
                            </ul>
                                <?php
                            }
                            ?>

                        </div><!--/.nav-collapse -->
                    </div><!--/.container -->
                </div><!--/.navbar-inner -->
            </div><!--/.navbar -->
        </div>