<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
    <img src="img/seguranca.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Seguran&ccedil;a</h1>
              <p class="lead">Para que a brincadeira termine com um final feliz, &eacute; preciso redefinir algumas pr&aacute;ticas h&aacute; muito tempo em uso na constru&ccedil;&atilde;o e manuten&ccedil;&atilde;o dos parquinhos infantis no Brasil.</p>
              <a class="btn btn-large btn-primary" href="#">Leia mais</a>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="img/girador.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Not&iacute;cias</h1>
              <p class="lead">Aqui nesta se&ccedil;&atilde;o, estaremos tentando mostrar um pouco o que h&aacute; de novo no Brasil e no mundo em termos de t&eacute;cnicas, normaliza&ccedil;&atilde;o, pol&iacute;ticas p&uacute;blicas, e das batalhas de outros pa&iacute;ses pra se melhorar parquinhos.</p>
              <a class="btn btn-large btn-primary" href="#">Leia mais</a>
            </div>
          </div>
        </div>
        <div class="item">
           <img src="img/gangora.jpg" alt="">
          <div class="container">
            <div class="carousel-caption">
              <h1>Parado no Tempo</h1>
              <p class="lead">&ldquo;Altamente defasados&rdquo; &eacute; como estamos hoje em compara&ccedil;&atilde;o com as novas tecnologias dispon&iacute;veis. Hoje &eacute; poss&iacute;vel com um pouco mais de investimento construir o que as crian&ccedil;as mais querem e precisam parquinhos seguros e divertidos </p>
              <a class="btn btn-large btn-primary" href="#">Leia mais</a>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->



    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="span4">
        
          <h2>Cadastre seu Parquinho aqui</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!-- /.span4 -->
        <div class="span4">
       
          <h2>Avalie seu parquinho</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!-- /.span4 -->
        <div class="span4">
          
          <h2>Passo a frente</h2>
          <p>&Eacute; hora de acordarmos. Todos sabemos que s&oacute; a iniciativa das pessoas &eacute; que vai mudar as coisas. Esperamos estar com este Website colaborando com essa mudan&ccedil;a.</p>
          <p><a class="btn" href="#">View details &raquo;</a></p>
        </div><!-- /.span4 -->
      </div><!-- /.row -->


    


